# config/database.yml

default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 20  # Solid Queueワーカー用に増加
  username: user
  password: password
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: 3306

development:
  primary: &primary_development
    <<: *default
    database: takt_development
  queue:
    <<: *primary_development
    database: takt_development_queue
    migrations_paths: db/queue_migrate

test:
  primary: &primary_test
    <<: *default
    database: takt_test
  queue:
    <<: *primary_test
    database: takt_test_queue
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    database: takt_production
    username: root
    password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: takt_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: takt_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: takt_production_cable
    migrations_paths: db/cable_migrate